### ISSUE TITLE
Polish ReactFinland

### ISSUE THREAD

**Issue by okonet** [ReactFinland/site#22]
- [x] Mobile version
- [x] Add padding on the mobile version
- [x] Improve the layout / composition
- [x] Fix the subscribe form layout
- [x] Make subscribe form stand out?
- [x] Use nicer icons on the speaker list for social links
- [x] Make the sponsor block stand out more?
- [x] Polish partners section
- [x] Style the tickets form a bit
- [x] Make schedule look better
- [x] Clean up "Organizers" 
- [x] Improve "For sponsors"
- [x] a11y 
- [x] Footer
- [x] Make "Buy Tickets" button look like a button
- [x] Reduce the letter spacing for the font in the navigation
- [x] Polish typography
- [x] Polish flags on the speakers page
- [x] Polish logo
- [x] More Finland in the teaser?
- [x] Split main and secondary links in the navigation
- [x] Make logo to navigate back home
- [x] Remove "Talks" section and put it to "Speakers"
- [x] Fix "No bio yet."

**Comment by okonet** [comment]
Some items still missing. Keeping open

**Comment by bebraw** [comment]
Sure. Can you point to the right font set at [Fontello](http://fontello.com/)? I can replace the fonts.

I already did some tuning for the remaining. I moved a couple to #26 and #27.
