### ISSUE TITLE
Fix organizers page layout

### ISSUE THREAD

**Issue by okonet** [ReactFinland/site#38]
![2018-01-30 at 16 14](https://user-images.githubusercontent.com/11071/35573921-b1242894-05d8-11e8-9136-d76114454572.png)

should have a better layout

**Comment by bebraw** [comment]
Yup, maybe we can do 4 and 3 instead of 6 and 1.

**Comment by manpenaloza** [comment]
@bebraw issue can be closed

**Comment by bebraw** [comment]
Good point. Closing.
