### ISSUE TITLE
Form inputs allow mysterious characters

### ISSUE THREAD

**Issue by thevangelist** [ReactFinland/site#43]
Form inputs on page https://react-finland.fi/#tickets allow using of other than numerical characters.

See example:

![screen shot 2018-02-05 at 9 46 47](https://user-images.githubusercontent.com/3482617/35793318-cc93953a-0a59-11e8-8b12-df8d62bfa06c.png)

**Comment by bebraw** [comment]
Could you ping [Tito](https://ti.to/) about this? They provide the form. I am not sure if there’s much I can do to fix it myself without some hackery.

**Comment by bebraw** [comment]
This isn't a problem anymore as we've migrated away from Tito.
